// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Bar
func (this *Bar) MarshalJSON() ([]byte, error) {
	str, err := BarMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Bar
func (this *Bar) UnmarshalJSON(b []byte) error {
	return BarUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	BarMarshaler   = &jsonpb.Marshaler{}
	BarUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
