// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Bar within kubernetes types, where deepcopy-gen is used.
func (in *Bar) DeepCopyInto(out *Bar) {
	p := proto.Clone(in).(*Bar)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bar. Required by controller-gen.
func (in *Bar) DeepCopy() *Bar {
	if in == nil {
		return nil
	}
	out := new(Bar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Bar. Required by controller-gen.
func (in *Bar) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
